#       https://github.com/docker/compose/releases/
# 	docker-compose.yaml  3.22.121  2018-07-03_17:30:04_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.21  
# 	   add LOCAL-HOST link to local host data in /usr/local/data/cluster 
# 	docker-compose.yaml  3.20.119  2018-06-29_10:01:07_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.19  
# 	   create blinkt color color functions 
# 	blinkt/docker-blinkt-workshop/labs/3.2/docker-compose.yaml  3.10.90  2018-06-25_20:11:55_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.09-3-ga1f8dbf  
# 	   add note for future updates 
# 	docker-compose.yaml  3.09.86  2018-06-24_22:25:49_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.08  
# 	   completed prototype controling blinkt from container start with docker-compose 
version: "2.0"
services: 
  display_blinkt:
    build:
      context: .
      args: 
        buildno: 1
    restart: unless-stopped
    privileged: true

##      example code for images and depends_on
#version: "2"
#services:
#  redis:
#    ports:
#      - 6379/TCP
#    image: aarch64/redis
#  counter:
#    ports:
#      - 3000/TCP
#    image: alexellis2/redis_hit_counter:aarch64
#    depends_on:
#     - redis
###
#       changes this file:
#         - start blinkt-monitor (display colors) on each host in cluster (chamge rainbow.py to display-led.py)
#         - start ___________ (write information
